services:
  db:
    image: postgres:16
    container_name: kanbanapp-postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: